### ISSUE TITLE
Market place is logged in but throws errors after adding Militia longsword and updating from marketplace.

### ISSUE THREAD

**Issue by Arielore** [ILikesCaviar/BDO_Enhancement_Tool#12]
The market remains connected in the MP login dialog. But after the first get from market after adding the militia longsword primary the application throws below on std_out. Manually messing up a price shows they are not refreshing.

Here is the error output on my fresh install;

Starting: 1618797079.295815
Traceback (most recent call last):
  File "c:\Python\Projects\BDO_Enhancement_Tool\common.py", line 366, in get_cost
    return self.get_prices(item_id)[grade]
  File "c:\Python\Projects\BDO_Enhancement_Tool\common.py", line 239, in __getitem__
    return self.prices[item]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python\Projects\BDO_Enhancement_Tool\Widgets\Abstract_FS_Table.py", line 136, in fs_gear_sig_gear_changed
    model.swap_gear(old_gear, this_gear)
  File "c:\Python\Projects\BDO_Enhancement_Tool\model.py", line 1251, in swap_gear
    self.edit_fs_item(old_gear, gear_obj)
  File "c:\Python\Projects\BDO_Enhancement_Tool\model.py", line 1201, in edit_fs_item
    self.add_fs_item(gear_obj)
  File "c:\Python\Projects\BDO_Enhancement_Tool\model.py", line 1165, in add_fs_item
    self.update_costs([this_gear])
  File "c:\Python\Projects\BDO_Enhancement_Tool\model.py", line 1331, in update_costs
    gear.set_base_item_cost(item_store.get_cost(gear, grade=0))
  File "c:\Python\Projects\BDO_Enhancement_Tool\common.py", line 370, in get_cost
    raise ItemStoreException('Item is not on the market')
BDO_Enhancement_Tool.common.ItemStoreException: Item is not on the market
Item is not on the market
Critical Message: Error contacting central market
Item is not on the market
Critical Message: Error contacting central market
Item is not on the market
Critical Message: Error contacting central market

**Comment by ILikesCaviar** [comment]
What's really weird is that I don't seem to get this error when I try. I think the commit I just pushed will fix this.

**Comment by Arielore** [comment]
The only thing left in common to the original install is an appdata config file. I included this file below  just in case it is important for recreating the fault between sessions. I will zap this folder next.

**Comment by Arielore** [comment]
Clearing the save file got rid of the problem behavior with Militia longsword so I probably managed to do something weird to that save file. 

The mess with the price and doing update all check still fails so I think its a separate unrelated thing that is still wrong with my build. A virus checker or something dumb?

**Comment by ILikesCaviar** [comment]
> Clearing the save file got rid of the problem behavior with Militia longsword so I probably managed to do something weird to that save file.
> 
> The mess with the price and doing update all check still fails so I think its a separate unrelated thing that is still wrong with my build. A virus checker or something dumb?

Oh, I'm sorry, I misunderstood. If you manually set the price it should block the item from being automatically set by the marketplace. The program currently lacks controls/features to turn this on/off for specific items. Currently, the way this is done (removing it from the item store) was the cause of this bug, and it is a bad idea. Removing the item this way should disable price updates for that item ID globally. Not good. Thanks for drawing attention to this. Clearly I need to rework how these two methods of setting a price interact with each other.
